const app = getApp();
const data = require('../../utils/data');
const predict = require('../../utils/predict');
const odds = require('../../utils/odds');
const names = require('../../utils/names');

// Live data (auto-generated by update-scores.js)
let liveOdds = {};
let liveInfo = {};
try { liveOdds = require('../../utils/odds-data'); } catch(e) {}
try { liveInfo = require('../../utils/info-data'); } catch(e) {}

Page({
  data: {
    match: null,
    pred: null,
    analysis: null,
    topScores: [],
    htFT: [],
    goalDist: [],
    histData: null,
    homeLineup: null,
    awayLineup: null,
    liveOdds: null,
    liveInjuries: null,
    marketConsensus: null,
    loading: true
  },

  onLoad(options) {
    const matchId = options.id;
    if (!matchId) { this.setData({ loading: false }); return; }
    this.buildDetail(matchId);
  },

  buildDetail(matchId) {
    const m = data.MATCH_SCHEDULE.find(x => x.id === matchId);
    if (!m) { this.setData({ loading: false }); return; }

    const ht = data.TEAMS.find(t => t.id === m.home);
    const at = data.TEAMS.find(t => t.id === m.away);
    if (!ht || !at) { this.setData({ loading: false }); return; }

    // Core prediction — pass live odds for market consensus
    const apiOdds = liveOdds[matchId] || null;
    const pred = predict.predictMatch(ht, at, apiOdds);
    const mol = data.MATCH_ODDS[matchId];

    // Top scores
    const topScoresList = odds.topScores(pred.expH, pred.expA, 6);

    // Half-time / full-time distribution
    const htftData = odds.calcHtFt(pred.expH, pred.expA);
    const htftResults = [
      { label: '胜-胜', prob: htftData.htH * pred.homeWinProb },
      { label: '平-胜', prob: htftData.htD * pred.homeWinProb },
      { label: '胜-平', prob: htftData.htH * pred.drawProb },
      { label: '平-平', prob: htftData.htD * pred.drawProb },
      { label: '负-胜', prob: htftData.htA * pred.homeWinProb },
      { label: '平-负', prob: htftData.htD * pred.awayWinProb },
      { label: '负-平', prob: htftData.htA * pred.drawProb },
      { label: '负-负', prob: htftData.htA * pred.awayWinProb },
      { label: '胜-负', prob: htftData.htH * pred.awayWinProb }
    ].sort((a, b) => b.prob - a.prob);
    const htftSum = htftResults.reduce((s, v) => s + v.prob, 0);
    htftResults.forEach(r => r.prob = r.prob / htftSum);

    // Total goals distribution
    const totG = odds.calcTotalGoals(pred.expH, pred.expA);

    // Historical data
    let histData = null;
    if (mol) {
      const hist = odds.getHistoricalDistribution(mol.h, mol.d, mol.a);
      if (hist && hist.total >= 3) {
        histData = {
          total: hist.total,
          hRate: (hist.hRate * 100).toFixed(0),
          dRate: (hist.dRate * 100).toFixed(0),
          aRate: (hist.aRate * 100).toFixed(0),
          hWins: hist.hWins,
          draws: hist.draws,
          aWins: hist.aWins,
          bucket: hist.coarseBucket || '',
          totalDataset: hist.totalDataset || 9557
        };
      }
    }

    // Fair odds
    let fairProbs = null;
    if (mol) {
      const fair = odds.oddsToFairProb(mol.h, mol.d, mol.a);
      fairProbs = {
        home: (fair.home * 100).toFixed(0),
        draw: (fair.draw * 100).toFixed(0),
        away: (fair.away * 100).toFixed(0)
      };
    }

    // Lineups — process player names to Chinese + jersey
    const fmtLineup = (lu) => {
      if (!lu) return null;
      const toP = (n) => {
        const clean = n.replace('(C)', '').trim();
        return {
          name: clean,
          cn: data.cnName(clean),
          num: data.JERSEY_NUM[clean] || data.JERSEY_NUM[n] || '?',
          isCaptain: n.includes('(C)')
        };
      };
      const all = [];
      if (lu.g) all.push(toP(lu.g));
      (lu.d || []).forEach(n => all.push(toP(n)));
      (lu.m || []).forEach(n => all.push(toP(n)));
      (lu.fwd || []).forEach(n => all.push(toP(n)));
      if (lu.subs) lu.subs.split(',').forEach(n => all.push(toP(n.trim())));
      return { f: lu.f, players: all, note: lu.note || '' };
    };
    const hLu = fmtLineup(data.STARTING_XI[m.home]);
    const aLu = fmtLineup(data.STARTING_XI[m.away]);

    // Generate textual analysis with live data
    const analysis = this.generateAnalysis(m, ht, at, pred, mol, apiInfo);

    // Update info
    const predLog = app.globalData.predLog || {};
    const logEntry = predLog[matchId];
    let updateInfo = '';
    if (logEntry && logEntry.lastUpdate) {
      const lu = new Date(logEntry.lastUpdate);
      const now = new Date();
      const diffMin = Math.floor((now - lu) / 60000);
      const ago = diffMin < 3 ? '刚刚' : diffMin < 60 ? diffMin+'分钟前' : Math.floor(diffMin/60)+'小时前';
      updateInfo = '🕐 ' + ago + '更新' + (logEntry.reason && logEntry.reason !== '定期更新' ? ' · '+logEntry.reason : '');
    }

    // Live injuries from API
    const apiInfo = liveInfo[matchId] || null;
    const apiInjuries = apiInfo ? apiInfo.injuries || [] : [];
    const homeInjuries = apiInjuries.filter(function(i) { return i.teamType === 'home'; });
    const awayInjuries = apiInjuries.filter(function(i) { return i.teamType === 'away'; });

    // Team stats from feature data
    const teamStats = apiInfo && apiInfo.feature ? {
      homeAvgGoals: apiInfo.feature.homeTeamAvgGoals || '-',
      awayAvgGoals: apiInfo.feature.awayTeamAvgGoals || '-',
      homeAvgLoss: apiInfo.feature.homeTeamAvgLossGoals || '-',
      awayAvgLoss: apiInfo.feature.awayTeamAvgLossGoals || '-',
      homeHomeWins: apiInfo.feature.homeTeamHomeWins || 0,
      homeHomeDraws: apiInfo.feature.homeTeamHomeDraws || 0,
      homeHomeLosses: apiInfo.feature.homeTeamHomeLosses || 0,
      awayAwayWins: apiInfo.feature.awayTeamAwayWins || 0,
      awayAwayDraws: apiInfo.feature.awayTeamAwayDraws || 0,
      awayAwayLosses: apiInfo.feature.awayTeamAwayLosses || 0,
    } : null;

    // Market consensus (AI vs live odds)
    const marketConsensus = pred.marketConsensus || null;

    this.setData({
      match: {
        id: m.id, date: m.date, time: m.time, venue: m.venue || 'TBD',
        group: m.grp, stage: m.stage,
        homeFlag: ht.flag, homeName: ht.cn, homeRank: ht.rk,
        homeAtt: ht.att, homeDef: ht.def, homeStr: predict.getStrength(ht).toFixed(1),
        homeNews: ht.news || '', homeInj: ht.inj || '',
        awayFlag: at.flag, awayName: at.cn, awayRank: at.rk,
        awayAtt: at.att, awayDef: at.def, awayStr: predict.getStrength(at).toFixed(1),
        awayNews: at.news || '', awayInj: at.inj || ''
      },
      pred: {
        score: pred.topScores.map(function(s) { return s.home + ':' + s.away; }).join(' · '),
        scores: pred.topScores,
        homeProb: (pred.homeWinProb * 100).toFixed(0),
        drawProb: (pred.drawProb * 100).toFixed(0),
        awayProb: (pred.awayWinProb * 100).toFixed(0),
        expH: pred.expH.toFixed(1),
        expA: pred.expA.toFixed(1),
        tacNarrative: (pred.tacAnalysis && pred.tacAnalysis.narrative) || '',
        tacAdjPct: (pred.tacAnalysis && pred.tacAnalysis.adjPct) || '',
        tacKeyPoints: (pred.tacAnalysis && pred.tacAnalysis.keyPoints) || [],
        homeStyle: (pred.tacAnalysis && pred.tacAnalysis.homeStyle) || '',
        awayStyle: (pred.tacAnalysis && pred.tacAnalysis.awayStyle) || '',
        tacticalAdj: pred.tacticalAdj
      },
      liveOdds: apiOdds,
      liveInjuries: apiInjuries,
      homeInjuries: homeInjuries,
      awayInjuries: awayInjuries,
      teamStats: teamStats,
      marketConsensus: marketConsensus,
      odds: mol ? { h: mol.h.toFixed(2), d: mol.d.toFixed(2), a: mol.a.toFixed(2) } : null,
      fairProbs,
      topScores: topScoresList.slice(0, 6).map(s => ({
        score: s.h + ':' + s.a,
        prob: (s.prob * 100).toFixed(1),
        isBest: pred.topScores.some(function(t) { return t.home === s.h && t.away === s.a; })
      })),
      htFT: htftResults.slice(0, 5).map(r => ({
        label: r.label, prob: (r.prob * 100).toFixed(1)
      })),
      goalDist: totG.labels.map((l, i) => ({
        label: l, prob: (totG.dist[i] * 100).toFixed(0),
        isExpected: i === Math.round(pred.expH + pred.expA)
      })),
      expTotalGoals: (pred.expH + pred.expA).toFixed(1),
      histData,
      homeLineup: hLu || null,
      awayLineup: aLu || null,
      analysis,
      updateInfo,
      loading: false
    });
  },

  generateAnalysis(m, ht, at, pred, mol, apiInfo) {
    const hTac = data.TACTICAL[ht.id] || {};
    const aTac = data.TACTICAL[at.id] || {};
    const hStr = predict.getStrength(ht), aStr = predict.getStrength(at);
    const gap = Math.abs(hStr - aStr);
    const gapDesc = gap > 15 ? '实力悬殊' : gap > 8 ? '差距明显' : gap > 4 ? '实力接近' : '势均力敌';
    const fav = hStr > aStr ? ht.cn : at.cn;
    const favProb = hStr > aStr ? (pred.homeWinProb*100).toFixed(0) : (pred.awayWinProb*100).toFixed(0);
    const parts = [];

    parts.push('📋 【比赛概述】本场' + ht.cn + '对阵' + at.cn + '，AI模型评定为"' + gapDesc + '"（' + fav + '取胜概率' + favProb + '%）。' + ht.cn + 'FIFA排名第' + ht.rk + '位，综合实力' + hStr.toFixed(1) + '；' + at.cn + 'FIFA排名第' + at.rk + '位，综合实力' + aStr.toFixed(1) + '。');

    // Live data: recent form
    if (apiInfo && apiInfo.recentForm && apiInfo.recentForm.home) {
      var hForm = apiInfo.recentForm.home;
      var aForm = apiInfo.recentForm.away || {};
      var feat = apiInfo.feature || {};
      parts.push('📊 【近期战绩】' + ht.cn + '：近' + (parseInt(hForm.homeTeamWins||0) + parseInt(hForm.homeTeamDraws||0) + parseInt(hForm.homeTeamLosses||0)) + '场 ' + hForm.homeTeamWins + '胜' + hForm.homeTeamDraws + '平' + hForm.homeTeamLosses + '负，胜率' + (hForm.homeTeamWinRate || '?') + '，场均进' + (feat.homeTeamAvgGoals || '?') + '球。' + at.cn + '：近' + (parseInt(aForm.awayTeamWins||0) + parseInt(aForm.awayTeamDraws||0) + parseInt(aForm.awayTeamLosses||0)) + '场 ' + (aForm.awayTeamWins||'?') + '胜' + (aForm.awayTeamDraws||'?') + '平' + (aForm.awayTeamLosses||'?') + '负，胜率' + (aForm.awayTeamWinRate || '?') + '。');
    }

    if (hTac.strength) parts.push('💪 【' + ht.cn + '优势】' + hTac.strength + '。短板：' + (hTac.weakness || '暂无明显短板') + '。');
    if (aTac.strength) parts.push('💪 【' + at.cn + '优势】' + aTac.strength + '。短板：' + (aTac.weakness || '暂无明显短板') + '。');

    if (pred.tacAnalysis) {
      let tac = '⚔️ 【战术博弈】' + pred.tacAnalysis.narrative + '（' + pred.tacAnalysis.adjPct + '）。';
      if (pred.tacAnalysis.keyPoints && pred.tacAnalysis.keyPoints.length > 0) {
        tac += '关键点：' + pred.tacAnalysis.keyPoints.slice(0,3).join('；') + '。';
      }
      parts.push(tac);
    }

    parts.push('⭐ 【核心球员】' + ht.cn + '：' + ht.stars.slice(0,2).join('、') + '。' + at.cn + '：' + at.stars.slice(0,2).join('、') + '。');

    // Market consensus from live odds
    if (pred.marketConsensus) {
      parts.push('🏷️ 【机构参考】' + pred.marketConsensus.label + '。机构隐含概率：' + ht.cn + '胜' + pred.marketConsensus.mktHome + '% / 平' + pred.marketConsensus.mktDraw + '% / ' + at.cn + '胜' + pred.marketConsensus.mktAway + '%。');
    }

    var topStr = pred.topScores.map(function(s) { return s.home + ':' + s.away; }).join(' · ');
    parts.push('🎯 【比分预测】AI预期进球' + pred.expH.toFixed(1) + '-' + pred.expA.toFixed(1) + '，最可能比分TOP3：' + topStr + '。模型推演' + ht.cn + '胜' + (pred.homeWinProb*100).toFixed(0) + '% / 平' + (pred.drawProb*100).toFixed(0) + '% / ' + at.cn + '胜' + (pred.awayWinProb*100).toFixed(0) + '%。');

    // Live injuries from API
    if (apiInfo && apiInfo.injuries && apiInfo.injuries.length > 0) {
      var injNames = apiInfo.injuries.map(function(i) {
        return (i.playerName || i.player) + (i.reason ? '(' + i.reason + ')' : '') + (i.isSuspended ? '[停赛]' : '');
      }).join('、');
      parts.push('🏥 【实时伤停】' + injNames + '。');
    } else if (ht.inj || at.inj) {
      let inj = '🏥 【伤病影响】';
      if (ht.inj) inj += ht.cn + '：' + ht.inj.replace(/[🔴⚠️]/g,'').trim() + '。';
      if (at.inj) inj += at.cn + '：' + at.inj.replace(/[🔴⚠️]/g,'').trim() + '。';
      parts.push(inj);
    }

    // Head-to-head history
    if (apiInfo && apiInfo.history && parseInt(apiInfo.history.totalMatches) > 0) {
      var hist = apiInfo.history;
      parts.push('📜 【历史交锋】双方交手' + hist.totalMatches + '次，' + ht.cn + ' ' + hist.wins + '胜' + hist.draws + '平' + hist.losses + '负，胜率' + (hist.winRate || '?') + '。');
    }

    const closeProb = Math.max(pred.homeWinProb, pred.drawProb, pred.awayWinProb);
    const closeResult = closeProb === pred.homeWinProb ? ht.cn+'取胜' : closeProb === pred.awayWinProb ? at.cn+'取胜' : '平局收场';
    const confidence = closeProb > 0.6 ? '较高信心' : closeProb > 0.45 ? '中等信心' : '偏低信心';
    parts.push('🔮 【综合研判】模型倾向' + closeResult + '（' + confidence + '）。走势将由' + (gap > 8 ? fav+'的发挥决定' : '双方临场和中场争夺决定') + '。');

    return parts;
  }
});
